language: php

php:
  - 7.2
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

git:
  depth: 1

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer update --no-interaction --prefer-source

script:
  - composer test

after_script:
  - |
    if [ -f "build/logs/clover.xml" ]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    fi
